substitutions:
  _SERVICE_NAME: sveltekit-run-hosting-example
steps:
  - id: 'build-image'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest
      - --dockerfile=Dockerfile
      - --cache=true
      - --cache-ttl=24h
    waitFor:
      - '-'
  - id: 'deploy-app'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', '${_SERVICE_NAME}', '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest', '--port', '3000', '--region', 'us-central1' ]
    waitFor:
      - 'build-image'
